default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: tanyapushchynska
  password: tanyapushchynska
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_engine_noney_development

test:
  <<: *default
  database: project_engine_noney_test

production:
  <<: *default
  database: project_engine_noney_production
  username: project_engine_noney
  password: <%= ENV['PROJECT_ENGINE_NONEY_DATABASE_PASSWORD'] %>
